name: build-packages

on:
  schedule:
    - cron: "0 2 * * *"
  pull_request:
    paths: &paths
      - ".dockerignore"
      - ".github/actions/docker-build/action.yaml"
      - ".github/workflows/build-packages.yaml"
      - "common/Makefile"
      - "org-config/*/packages/**"
      - "packages/**"
  push:
    branches:
      - main
    paths: *paths
  workflow_dispatch:

permissions: {}

# When a PR is updated, cancel the jobs from the previous version. Merges
# do not define head_ref, so use run_id to never cancel those jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  identify-jobs:
    name: identify-jobs
    environment:
      name: upstream-build
      deployment: false
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    timeout-minutes: 10
    # FIXME: change to ubuntu-latest when ubuntu-latest is Ubuntu 26.04.
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Generate Build Matrix
        id: set-matrix
        shell: bash
        run: |
          # Files/directories that trigger rebuild of everything.
          ALL_PATTERN="\.github\/|\.dockerignore|common\/Makefile"
          # Package changes, only rebuild the specific packages.
          PACKAGES_PATTERN="packages\/"
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            git fetch origin $GITHUB_PR_BASE_REF
            all_files=$(git diff --name-only origin/$GITHUB_PR_BASE_REF HEAD)
          elif [ "$GITHUB_EVENT_NAME" = "push" ]; then
            all_files=$(git diff --name-only $GITHUB_EVENT_BEFORE $GITHUB_EVENT_AFTER)
          fi
          declare -a PKGS
          # Rebuild everything on CI changes and schedule/manual trigger.
          if [[ $all_files =~ $ALL_PATTERN ]] || [ "$GITHUB_EVENT_NAME" = "schedule" ] || [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
            DIRS=$(ls -l packages/ | grep -E ^d | awk '{print $9}')
            for d in $DIRS; do
              PKGS+=("$d")
            done
          elif [[ $all_files =~ $PACKAGES_PATTERN ]]; then
            CFG_PATTERN="\/packages\/"
            for file in $all_files; do
              if [[ $file =~ $CFG_PATTERN ]]; then
                PKGS1=$(echo $file | awk -F/packages/ '{print $2}' | awk -F/ '{print $1}')
              elif [[ $file =~ $PACKAGES_PATTERN ]]; then
                PKGS1=$(echo $file | awk -Fpackages/ '{print $2}' | awk -F/ '{print $1}')
              fi
              if [[ ! " ${PKGS[*]} " =~ " ${PKGS1} " ]]; then
                PKGS+=("$PKGS1")
              fi
            done
          fi
          tmp=""
          for pkg in "${PKGS[@]}"; do
            BUILD_TIMEOUT=$(make --no-print-directory -C packages/$pkg build-timeout)
            EXTRA_REPOSITORY=$(make --no-print-directory -C packages/$pkg extra-build-repository)
            if [ "$tmp" != "" ]; then
              tmp+=","
            fi
            tmp+="{\"package\": \"$pkg\", \"build-timeout\": $BUILD_TIMEOUT, \"extra-repository\": \"$EXTRA_REPOSITORY\"}"
          done
          if [ "$tmp" = "" ]; then
            echo "Internal error: no changes detected. Debug info (all_files): $all_files"
            exit 1
          fi
          echo "matrix={\"include\":[$tmp]}" >> $GITHUB_OUTPUT
        env:
          CI_REGISTRY: ${{ vars.CI_REGISTRY }}
          CI_REGISTRY_BASE_PATH: ${{ vars.CI_REGISTRY_BASE_PATH }}
          GITHUB_EVENT_AFTER: ${{ github.event.after }}
          GITHUB_EVENT_BEFORE: ${{ github.event.before }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
          ORGANIZATION_NAME: ${{ vars.ORGANIZATION_NAME }}

  build-image:
    name: build-image
    needs:
      - identify-jobs
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.identify-jobs.outputs.matrix) }}
    environment:
      name: upstream-build
      deployment: false
    timeout-minutes: ${{ matrix.build-timeout }}
    # FIXME: change to ubuntu-latest when ubuntu-latest is Ubuntu 26.04.
    runs-on: ubuntu-26.04
    permissions:
      id-token: write # This is required for cosign
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Docker Build
        uses: ./.github/actions/docker-build
        with:
          build-path: packages/${{ matrix.package }}
          ci-registry: ${{ vars.CI_REGISTRY }}
          ci-registry-base-path: ${{ vars.CI_REGISTRY_BASE_PATH }}
          ci-registry-upstream-base-path: ${{ vars.CI_REGISTRY_UPSTREAM_BASE_PATH }}
          do-push: ${{ github.ref == 'refs/heads/main' }}
          docker-auth-config: ${{ secrets.DOCKER_AUTH_CONFIG_RW }}
          extra-repository: ${{ matrix.extra-repository }}
          extra-repository-token: ${{ secrets.PAT_EXTRA_REPO_RO }}
          organization-name: ${{ vars.ORGANIZATION_NAME }}
