name: upstream-build

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/upstream-build.yaml"
      - "common/Makefile"
      - "upstream"
  workflow_dispatch:

permissions: {}

# When a PR is updated, cancel the jobs from the previous version. Merges
# do not define head_ref, so use run_id to never cancel those jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  upstream-build:
    name: upstream-build
    environment:
      name: upstream-build
      deployment: false
    timeout-minutes: 300
    # FIXME: change to ubuntu-latest when ubuntu-latest is Ubuntu 26.04.
    runs-on: ubuntu-26.04
    permissions:
      id-token: write # This is required for cosign
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Get Git commit timestamps
        run: |
          TIMESTAMP=$(git log -1 --pretty=%ct .)
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Install cosign
        if: github.ref == 'refs/heads/main'
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Configure to push
        if: github.ref == 'refs/heads/main'
        run: |
          echo "PUSH_CMD=docker" >> $GITHUB_ENV
          echo "PUSH_OPTION=--push" >> $GITHUB_ENV
          echo "COSIGN_CMD=cosign" >> $GITHUB_ENV

      - name: Build upstream images
        run: |
          set -o pipefail
          # Unset empty commands for check in Makefile.
          [ -n "$COSIGN_CMD" ] || unset COSIGN_CMD
          [ -n "$PUSH_CMD" ] || unset PUSH_CMD
          [ -n "$PUSH_OPTION" ] || unset PUSH_OPTION
          export BUILDKIT_PROGRESS=plain
          export Q=''
          export DOCKER_EXTRA_UPSTREAM_ARGS="--pull --no-cache"
          # Build buildpack-deps/Ubuntu first, but build the other images even if it fails.
          make -k -C upstream DIRS=buildpack-deps -j2 all || true
          # Independent builds, so keep going to get non-failing images updated.
          make -k -C upstream -j2 all
        env:
          CI_REGISTRY: ${{ vars.CI_REGISTRY }}
          CI_REGISTRY_BASE_PATH: ${{ vars.CI_REGISTRY_UPSTREAM_BASE_PATH }}
          COSIGN_CMD: ${{ env.COSIGN_CMD }}
          DOCKER_AUTH_CONFIG: ${{ secrets.DOCKER_AUTH_CONFIG_UPSTREAM_RW }}
          ORGANIZATION_NAME: ${{ vars.ORGANIZATION_NAME }}
          PUSH_CMD: ${{ env.PUSH_CMD }}
          PUSH_OPTION: ${{ env.PUSH_OPTION }}
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}

  # This job requires secrets from the repository, and those aren't exposed
  # in pull requests from forks. Testing changes to this job in a pull request
  # needs to be done from a branch of the repository itself.
  upstream-transfer:
    name: upstream-transfer
    if: github.ref == 'refs/heads/main'
    needs:
      - upstream-build
    environment:
      name: upstream-build
      deployment: false
    timeout-minutes: 10
    # FIXME: change to ubuntu-latest when ubuntu-latest is Ubuntu 26.04.
    runs-on: ubuntu-26.04
    # Variables/secrets in the container block are evaluated before the environment
    # variables, so these variables need to be defined at the repository level.
    container:
      # FIXME: use releases for version when we have that up and running on GitHub.
      image: ${{ vars.CI_REGISTRY }}/${{ vars.CI_REGISTRY_BASE_PATH }}/support-releaser:latest # zizmor: ignore[unpinned-images]
      credentials:
        username: ${{ vars.CI_REGISTRY_READ_USER }}
        password: ${{ secrets.CI_REGISTRY_READ_USER_PASSWORD }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get Git information
        run: |
          # Running in a container requires to set safe directory manually.
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          SHORT_SHA=$(git rev-parse --short ${GITHUB_SHA})
          echo "COMMIT_SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
        env:
          GITHUB_SHA: ${{ github.sha }}

      - name: Transfer upstream images
        run: |
          make -C upstream upstream-transfer
        env:
          CI_REGISTRY: ${{ vars.CI_REGISTRY }}
          CI_REGISTRY_BASE_PATH: ${{ vars.CI_REGISTRY_BASE_PATH }}
          CI_REGISTRY_UPSTREAM_PATH: ${{ vars.CI_REGISTRY_UPSTREAM_BASE_PATH }}
          COMMIT_SHORT_SHA: ${{ env.COMMIT_SHORT_SHA }}
          DOCKER_AUTH_CONFIG: ${{ secrets.DOCKER_AUTH_CONFIG_RW }}
          UPSTREAM_IMAGES: ${{ vars.UPSTREAM_IMAGES }}
